site_name: {{cookiecutter.project_name}}
{% if cookiecutter.hp250 == 'y' %}
repo_url: https://hp250.fritz.box/git/{{cookiecutter.org_github_handle}}/{{cookiecutter.project_name}}
site_url: https://hp250.fritz.box/git/{{cookiecutter.org_github_handle}}/{{cookiecutter.project_name}}
{%- else -%}
repo_url: https://github.com/{{cookiecutter.author_github_handle}}/{{cookiecutter.project_name}}
site_url: https://{{cookiecutter.author_github_handle}}.github.io/{{cookiecutter.project_name}}
{%- endif -%}
site_description: {{cookiecutter.project_description}}
site_author: {{cookiecutter.author}}
edit_uri: edit/main/docs/
repo_name: {{cookiecutter.org_github_handle}}/{{cookiecutter.project_name}}
{% if cookiecutter.hp250 == 'y' %}
copyright: Maintained by <a href="https://hp250.fritz.box/git/{cookiecutter.author_github_handle}}.com">{{cookiecutter.author_github_handle}}</a>.
{%- else -%}
copyright: Maintained by <a href="https://github.com/{cookiecutter.author_github_handle}}.com">{{cookiecutter.author_github_handle}}</a>.
{%- endif -%}

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [
            {%- if cookiecutter.layout == "src" -%}
            "src/{{cookiecutter.project_slug}}"
            {%- else -%}
            "{{cookiecutter.project_slug}}"
            {%- endif -%}
            ]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
{% if cookiecutter.hp250 == 'y' %}
      link: https://hp250.fritz.box/git/{{cookiecutter.org_github_handle}}/{{cookiecutter.project_name}}
{%- else -%}
      link: https://github.com/{{cookiecutter.author_github_handle}}/{{cookiecutter.project_name}}
{%- endif -%}
    - icon: fontawesome/brands/python
{% if cookiecutter.hp250 == 'y' %}
      link: https://hp250.fritz.box/git/{{cookiecutter.org_github_handle}}/-/packages/pypi/{{cookiecutter.project_name}}
{%- else -%}
      link: https://pypi.org/project/{{cookiecutter.project_name}}
{%- endif -%}

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
